[package]
name = "rust-demystified"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
component = "0.1.1"
rust-analyzer = "0.0.1"
serde = { version = "1.0.211", features = ["derive", "rc"] }
serde_json = "1.0.132"
